### ISSUE TITLE
Union types broken when cache is enabled

### ISSUE THREAD

**Issue by ddedic** [nuwave/lighthouse#1004]
Using Unions in cache disabled environment works as expected.
When cache is enabled, same code that worked in previous environment does not work anymore

**Expected behavior/Solution**
It should return result same as in cache=disabled environment.

**Steps to reproduce**

1. Create sample query type that returns Union type
2. Disable cache in your .env file LIGHTHOUSE_CACHE_ENABLE=false
3. Run query => Everything is ok.
4. Enable cache in your .env file LIGHTHOUSE_CACHE_ENABLE=true
5. Run query => It breaks

**Output/Logs**

<details><summary>Click to expand</summary>

```
{
  "errors": [
    {
      "debugMessage": "array_map(): Argument #2 should be an array",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "eventsCalendar",
        0,
        "events",
        0
      ],
      "trace": [
        {
          "file": "/var/www/vendor/nuwave/lighthouse/src/Schema/TypeRegistry.php",
          "line": 428,
          "function": "array_map(instance of Closure, instance of GraphQL\\Language\\AST\\NodeList(2))"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Type/Definition/UnionType.php",
          "line": 76,
          "call": "Nuwave\\Lighthouse\\Schema\\TypeRegistry::Nuwave\\Lighthouse\\Schema\\{closure}()"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Type/Definition/UnionType.php",
          "line": 59,
          "call": "GraphQL\\Type\\Definition\\UnionType::getTypes()"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Type/Schema.php",
          "line": 427,
          "call": "GraphQL\\Type\\Definition\\UnionType::isPossibleType(GraphQLType: Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1343,
          "call": "GraphQL\\Type\\Schema::isPossibleType(GraphQLType: EventCalendarDayDataType, GraphQLType: Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1038,
          "call": "GraphQL\\Executor\\ReferenceExecutor::ensureValidRuntimeType(GraphQLType: Event, GraphQLType: EventCalendarDayDataType, instance of GraphQL\\Type\\Definition\\ResolveInfo, instance of App\\Models\\Events\\Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 849,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeAbstractValue(GraphQLType: EventCalendarDayDataType, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(4), instance of App\\Models\\Events\\Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 726,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: EventCalendarDayDataType, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(4), instance of App\\Models\\Events\\Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 677,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValueWithLocatedError(GraphQLType: EventCalendarDayDataType, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(4), instance of App\\Models\\Events\\Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 952,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValueCatchingError(GraphQLType: EventCalendarDayDataType, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(4), instance of App\\Models\\Events\\Event)"
        },
        {
          "file": "/var/www/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 821,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeListValue(GraphQLType: EventCalendarDayDataType, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(3), instance of Illuminate\\Support\\Collection(1))"
        }

.... [rest of the exception]
```

</details></br>

**Environment**

Lighthouse Version: 4.4.0
Laravel Version: 6.2.0

**Comment by Yalian** [comment]
the same here, even the first time runs ok because the type array come correctly 
![image](https://user-images.githubusercontent.com/28605214/66776198-7d34fc00-ee8b-11e9-909e-21c21eb9f859.png)

but the second time the array contains another array 
![image](https://user-images.githubusercontent.com/28605214/66776236-9a69ca80-ee8b-11e9-9916-376881342fd1.png)

and boom!

**Comment by stayallive** [comment]
Same here, that took down our app :)

I have a stacktrace of the culprit (I believe) that might be of help:

```
ErrorException: array_map(): Argument #2 should be an array
#60 [internal](0): array_map
#59 /vendor/nuwave/lighthouse/src/Schema/TypeRegistry.php(428): Nuwave\Lighthouse\Schema\TypeRegistry::Nuwave\Lighthouse\Schema\{closure}
#58 /vendor/webonyx/graphql-php/src/Type/Definition/UnionType.php(76): GraphQL\Type\Definition\UnionType::getTypes
#57 /vendor/webonyx/graphql-php/src/Validator/Rules/PossibleFragmentSpreads.php(103): GraphQL\Validator\Rules\PossibleFragmentSpreads::doTypesOverlap
#56 /vendor/webonyx/graphql-php/src/Validator/Rules/PossibleFragmentSpreads.php(32): GraphQL\Validator\Rules\PossibleFragmentSpreads::GraphQL\Validator\Rules\{closure}
#55 /vendor/webonyx/graphql-php/src/Language/Visitor.php(410): GraphQL\Language\Visitor::GraphQL\Language\{closure}
#54 /vendor/webonyx/graphql-php/src/Language/Visitor.php(466): GraphQL\Language\Visitor::GraphQL\Language\{closure}
#53 /vendor/webonyx/graphql-php/src/Language/Visitor.php(273): GraphQL\Language\Visitor::visit
#52 /vendor/webonyx/graphql-php/src/Validator/DocumentValidator.php(226): GraphQL\Validator\DocumentValidator::visitUsingRules
#51 /vendor/webonyx/graphql-php/src/Validator/DocumentValidator.php(118): GraphQL\Validator\DocumentValidator::validate
#50 /vendor/webonyx/graphql-php/src/GraphQL.php(149): GraphQL\GraphQL::promiseToExecute
#49 /vendor/webonyx/graphql-php/src/GraphQL.php(98): GraphQL\GraphQL::executeQuery
#48 /vendor/nuwave/lighthouse/src/GraphQL.php(170): Nuwave\Lighthouse\GraphQL::executeQuery
#47 /vendor/nuwave/lighthouse/src/GraphQL.php(109): Nuwave\Lighthouse\GraphQL::executeRequest
#46 /vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(70): Nuwave\Lighthouse\Support\Http\Controllers\GraphQLController::query
#45 [internal](0): call_user_func_array
```

**Comment by spawnia** [comment]
Released the fix in https://github.com/nuwave/lighthouse/releases/tag/v4.5.0

**Comment by georgeboot** [comment]
@spawnia I've just installed the `dev-master` version, but are getting the same issue **_when I am activating the defer extension_**.

Could this be related?

**Comment by spawnia** [comment]
What is the exact error you are getting? (It can not be the same as `array_map` is no longer used)

**Comment by georgeboot** [comment]
```json
{
  "message": "array_map(): Expected parameter 2 to be an array, object given",
  "exception": "ErrorException",
  "file": "/Users/george/Sites/my-project/vendor/nuwave/lighthouse/src/Schema/Factories/ClientDirectiveFactory.php",
  "line": 64,
  "trace": [
    ...
  ]
}
```

Version: `nuwave/lighthouse v4.5.0` on `Laravel Framework 6.3.0`.
