### ISSUE TITLE
GraphQL server is not checking the required variables and passing to the resolver

### ISSUE THREAD

**Issue by ssi-anik** [nuwave/lighthouse#1710]
**Describe the bug**
GraphQL Server is not validating the existence of the variables.
![image](https://user-images.githubusercontent.com/2676602/106351157-adb0db80-6304-11eb-8185-c3506cfb8997.png)

<hr/>
But if the server receives the variables, it works fine.

![image](https://user-images.githubusercontent.com/2676602/106351246-54957780-6305-11eb-8957-7c60900152e1.png)

**Expected behavior/Solution**
If the client doesn't provide the values to the GraphQL server, it should invalidate the request rather than passing to the resolver.

**Steps to reproduce**
I have no idea how to reproduce. It was working fine last night. But all of a sudden, it started to work unexpectedly. 

**Output/Logs**

<details><summary>Click to expand</summary>

```
local.ERROR: Undefined index: username {"exception":"[object] (ErrorException(code: 0): Undefined index: username at /var/www/html/app/GraphQL/Mutations/UserLogin.php:12)
[stacktrace]
#0 /var/www/html/app/GraphQL/Mutations/UserLogin.php(12): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(8, 'Undefined index...', '/var/www/html/a...', 12, Array)
#1 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/FieldDirective.php(51): App\\GraphQL\\Mutations\\UserLogin->__invoke(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#2 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/RenameArgsDirective.php(34): Nuwave\\Lighthouse\\Schema\\Directives\\FieldDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#3 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/SpreadDirective.php(35): Nuwave\\Lighthouse\\Schema\\Directives\\RenameArgsDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#4 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/ArgTraversalDirective.php(29): Nuwave\\Lighthouse\\Schema\\Directives\\SpreadDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#5 /var/www/html/vendor/nuwave/lighthouse/src/Validation/ValidateDirective.php(60): Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#6 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/ArgTraversalDirective.php(29): Nuwave\\Lighthouse\\Validation\\ValidateDirective->Nuwave\\Lighthouse\\Validation\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#7 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Directives/TrimDirective.php(56): Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#8 /var/www/html/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php(92): Nuwave\\Lighthouse\\Schema\\Directives\\TrimDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#9 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(624): Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory->Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(NULL, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#10 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\\Executor\\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\\Type\\Definition\\FieldDefinition), Object(GraphQL\\Language\\AST\\FieldNode), Object(Closure), NULL, Object(GraphQL\\Type\\Definition\\ResolveInfo))
#11 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(474): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#12 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(858): GraphQL\\Executor\\ReferenceExecutor->GraphQL\\Executor\\{closure}(Array, 'login')
#13 [internal function]: GraphQL\\Executor\\ReferenceExecutor->GraphQL\\Executor\\{closure}(Array, 'login')
#14 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(860): array_reduce(Array, Object(Closure), Array)
#15 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(490): GraphQL\\Executor\\ReferenceExecutor->promiseReduce(Array, Object(Closure), Array)
#16 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(263): GraphQL\\Executor\\ReferenceExecutor->executeFieldsSerially(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Object(ArrayObject))
#17 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\\Executor\\ReferenceExecutor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#18 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#19 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL)
#20 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), 'mutation ($inpu...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL, Array)
#21 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(195): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), 'mutation ($inpu...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL, Array)
#22 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(138): Nuwave\\Lighthouse\\GraphQL->executeQuery('mutation ($inpu...', Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL)
#23 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(118): Nuwave\\Lighthouse\\GraphQL->executeOperation(Object(GraphQL\\Server\\OperationParams))
#24 /var/www/html/vendor/nuwave/lighthouse/src/Support/Utils.php(91): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}(Object(GraphQL\\Server\\OperationParams))
#25 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(102): Nuwave\\Lighthouse\\Support\\Utils::applyEach(Object(Closure), Object(GraphQL\\Server\\OperationParams))
#26 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(28): Nuwave\\Lighthouse\\GraphQL->executeRequest(Object(Laravel\\Lumen\\Http\\Request), Object(Laragraph\\Utils\\RequestParser), Object(GraphQL\\Server\\Helper))
#27 /var/www/html/vendor/illuminate/container/BoundMethod.php(36): Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->__invoke(Object(Laravel\\Lumen\\Http\\Request), Object(Nuwave\\Lighthouse\\GraphQL), Object(Illuminate\\Events\\Dispatcher), Object(Laragraph\\Utils\\RequestParser), Object(GraphQL\\Server\\Helper), Object(Nuwave\\Lighthouse\\Execution\\SingleResponse))
#28 /var/www/html/vendor/illuminate/container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /var/www/html/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#30 /var/www/html/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#31 /var/www/html/vendor/illuminate/container/Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#32 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(386): Illuminate\\Container\\Container->call(Array, Array)
#33 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(329): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#34 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(279): Laravel\\Lumen\\Application->callControllerAction(Array)
#35 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(259): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#36 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#37 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AttemptAuthentication.php(32): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#38 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#39 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#40 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php(27): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#41 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#42 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#43 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#44 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(260): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#46 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(166): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#47 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#48 /var/www/html/app/Http/Middleware/QueryLoggerMiddleware.php(43): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#49 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(167): App\\Http\\Middleware\\QueryLoggerMiddleware->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#50 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#51 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#52 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#53 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#54 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#55 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(172): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#57 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(109): Laravel\\Lumen\\Application->dispatch(NULL)
#58 /var/www/html/public/index.php(28): Laravel\\Lumen\\Application->run()
#59 {main}
```

</details></br>

**Lighthouse Version**
**5.1.0**
![image](https://user-images.githubusercontent.com/2676602/106351276-860e4300-6305-11eb-914e-40f31758e76e.png)

**Comment by ssi-anik** [comment]
I am extremely sorry to raise this issue. My bad. I didn't put the `!` sign after the input type. I am sorry. Closing the issue.
