### ISSUE TITLE
Unable to install lighthouse using tutorial.

### ISSUE THREAD

**Issue by GrzegorzDrozd** [nuwave/lighthouse#1743]
**Describe the bug**
Tutorial https://lighthouse-php.com/3.0/getting-started/installation.html#install-via-composer does not work.

**Expected behavior/Solution**

Following tutorial: application should work.

**Steps to reproduce**

Following tutorial i am doing those operations:
```
@echo off
\work\php-8.0.2-Win32-vs16-x64\php.exe -f composer.phar create-project laravel/laravel lighthouse-test
copy composer.phar lighthouse-test
cd lighthouse-test

echo "Laravel config: db, app name etc. (1) Press enter when done"
pause
\work\php-8.0.2-Win32-vs16-x64\php.exe -f artisan config:cache
\work\php-8.0.2-Win32-vs16-x64\php.exe -f artisan migrate


\work\php-8.0.2-Win32-vs16-x64\php.exe -f composer.phar require nuwave/lighthouse
echo "Register service providers. (2) Press enter when done"
pause
\work\php-8.0.2-Win32-vs16-x64\php.exe -f artisan vendor:publish --tag=lighthouse-schema
\work\php-8.0.2-Win32-vs16-x64\php.exe -f artisan config:cache
```

I am using correct .env file, database migration works, tables are created - after (1).
I am adding following lines into app/bootstrap at point (2):
```
$app->register(Nuwave\Lighthouse\LighthouseServiceProvider::class);
$app->register(Nuwave\Lighthouse\GlobalId\GlobalIdServiceProvider::class);
$app->register(Nuwave\Lighthouse\OrderBy\OrderByServiceProvider::class);
$app->register(Nuwave\Lighthouse\Pagination\PaginationServiceProvider::class);
$app->register(Nuwave\Lighthouse\Scout\ScoutServiceProvider::class);
$app->register(Nuwave\Lighthouse\SoftDeletes\SoftDeletesServiceProvider::class);
$app->register(Nuwave\Lighthouse\Validation\ValidationServiceProvide::class);

return $app;
```

**Output/Logs**

Just after running this line:
```
\work\php-8.0.2-Win32-vs16-x64\php.exe -f composer.phar require nuwave/lighthouse
```
Every artisan operation ends with: 
```
PHP Fatal error:  Uncaught ReflectionException: Class "env" does not exist in \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Container\Container.php:830
Stack trace:
#0 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(830): ReflectionClass->__construct('env')
#1 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(712): Illuminate\Container\Container->build('env')
#2 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(841): Illuminate\Container\Container->resolve('env', Array, true)
#3 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Foundation\Application->resolve('env', Array)
#4 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(826): Illuminate\Container\Container->make('env', Array)
#5 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(1358): Illuminate\Foundation\Application->make('env')
#6 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(631): Illuminate\Container\Container->offsetGet('env')
#7 \work\lighthouse-test\vendor\nuwave\lighthouse\src\LighthouseServiceProvider.php(156): Illuminate\Foundation\Application->runningUnitTests()
#8 \work\lighthouse-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(672): Nuwave\Lighthouse\LighthouseServiceProvider->register()
#9 \work\lighthouse-test\bootstrap\app.php(56): Illuminate\Foundation\Application->register(Object(Nuwave\Lighthouse\LighthouseServiceProvider))
```

**Lighthouse Version**
Versions:
```
doctrine/annotations                 1.12.1 
doctrine/cache                       1.10.2 
doctrine/collections                 1.6.7  
doctrine/common                      3.1.1  
doctrine/dbal                        2.12.1 
doctrine/event-manager               1.1.1  
doctrine/inflector                   2.0.3  
doctrine/instantiator                1.4.0  
doctrine/lexer                       1.2.1  
doctrine/orm                         2.8.2  
doctrine/persistence                 2.1.0  

nuwave/lighthouse                    v5.2.0

laravel/framework                    v8.29.0
webonyx/graphql-php                  v14.5.1 
```

**Comment by spawnia** [comment]
Do not add anything to `app/bootstrap`.

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.

**Comment by GrzegorzDrozd** [comment]
Yeah - sorry. I was following tutorial and I missed that I need to add that ONLY when using Lumen (and not full Laravel).
