### ISSUE TITLE
@hasOne / @hasMany Argument 1 passed to RelationDirective must be an instance of Illuminate\\Database\\Eloquent\\Model, array given

### ISSUE THREAD

**Issue by figurluk** [nuwave/lighthouse#1913]
**Describe the bug**

When I call the following query: 
`query Me {
  me {
    id
    organization {
      id
      name
      events {
        id
      }
    }
  }
}`

I receive the error: Argument 1 passed to Nuwave\\Lighthouse\\Schema\\Directives\\RelationDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}() must be an instance of Illuminate\\Database\\Eloquent\\Model, array given, called in /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/RenameArgsDirective.php on line 33

**schema:** 

type Query {
    me: User
}

type User {
    id: ID!
    organization: Organization @hasOne
}

type Organization {
    id: ID!
    events: [Event!]! @hasMany
}

type Event {
    id: ID!
}

**Expected behavior/Solution**

the relation fields will be correctly resolved and returned :)

**Output/Logs**

<details><summary>Click to expand</summary>

```
[2021-08-12 10:05:50] local.ERROR: Argument 1 passed to Nuwave\Lighthouse\Schema\Directives\RelationDirective::Nuwave\Lighthouse\Schema\Directives\{closure}() must be an instance of Illuminate\Database\Eloquent\Model, array given, called in /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/RenameArgsDirective.php on line 33 {"userId":3,"exception":"[object] (TypeError(code: 0): Argument 1 passed to Nuwave\\Lighthouse\\Schema\\Directives\\RelationDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}() must be an instance of Illuminate\\Database\\Eloquent\\Model, array given, called in /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/RenameArgsDirective.php on line 33 at /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/RelationDirective.php:29)
[stacktrace]
#0 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/RenameArgsDirective.php(33): Nuwave\\Lighthouse\\Schema\\Directives\\RelationDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#1 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/SpreadDirective.php(34): Nuwave\\Lighthouse\\Schema\\Directives\\RenameArgsDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#2 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/ArgTraversalDirective.php(29): Nuwave\\Lighthouse\\Schema\\Directives\\SpreadDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#3 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Validation/ValidateDirective.php(53): Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#4 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/ArgTraversalDirective.php(29): Nuwave\\Lighthouse\\Validation\\ValidateDirective->Nuwave\\Lighthouse\\Validation\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#5 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Directives/TrimDirective.php(56): Nuwave\\Lighthouse\\Schema\\Directives\\ArgTraversalDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#6 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php(92): Nuwave\\Lighthouse\\Schema\\Directives\\TrimDirective->Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#7 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(623): Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory->Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(Array, Array, Object(Nuwave\\Lighthouse\\Schema\\Context), Object(GraphQL\\Type\\Definition\\ResolveInfo))
#8 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(550): GraphQL\\Executor\\ReferenceExecutor->resolveFieldValueOrError(Object(GraphQL\\Type\\Definition\\FieldDefinition), Object(GraphQL\\Language\\AST\\FieldNode), Object(Closure), Array, Object(GraphQL\\Type\\Definition\\ResolveInfo))
#9 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), Array, Object(ArrayObject), Array)
#10 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), Array, Array, Object(ArrayObject))
#11 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\\Executor\\ReferenceExecutor->collectAndExecuteSubfields(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Array, Array)
#12 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(793): GraphQL\\Executor\\ReferenceExecutor->completeObjectValue(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#13 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#14 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#15 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), Array, Object(ArrayObject), Array)
#16 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), Array, Array, Object(ArrayObject))
#17 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\\Executor\\ReferenceExecutor->collectAndExecuteSubfields(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Array, Array)
#18 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(793): GraphQL\\Executor\\ReferenceExecutor->completeObjectValue(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#19 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#20 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ObjectType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Array)
#21 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#22 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(264): GraphQL\\Executor\\ReferenceExecutor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Object(ArrayObject))
#23 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\\Executor\\ReferenceExecutor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#24 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#25 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, 'Me', NULL)
#26 /Users/lukas/Code/lekar-pro-api/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, 'Me', NULL, Array)
#27 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/GraphQL.php(213): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, 'Me', NULL, Array)
#28 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/GraphQL.php(164): Nuwave\\Lighthouse\\GraphQL->executeQuery(Object(GraphQL\\Language\\AST\\DocumentNode), Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, 'Me')
#29 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/GraphQL.php(118): Nuwave\\Lighthouse\\GraphQL->executeOperation(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Schema\\Context))
#30 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Support/Utils.php(98): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}(Object(GraphQL\\Server\\OperationParams))
#31 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/GraphQL.php(117): Nuwave\\Lighthouse\\Support\\Utils::applyEach(Object(Closure), Object(GraphQL\\Server\\OperationParams))
#32 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Schema\\Context))
#33 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->__invoke(Object(Illuminate\\Http\\Request), Object(Nuwave\\Lighthouse\\GraphQL), Object(Illuminate\\Events\\Dispatcher), Object(Laragraph\\Utils\\RequestParser), Object(Nuwave\\Lighthouse\\Execution\\SingleResponse), Object(Nuwave\\Lighthouse\\Execution\\ContextFactory))
#34 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController), '__invoke')
#35 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#36 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#37 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AttemptAuthentication.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/lukas/Code/lekar-pro-api/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#44 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#45 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#46 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#47 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#48 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/lukas/Code/lekar-pro-api/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/lukas/Code/lekar-pro-api/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/lukas/Code/lekar-pro-api/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /Users/lukas/Code/lekar-pro-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#68 /Users/lukas/Code/lekar-pro-api/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#69 /Users/lukas/.composer/vendor/laravel/valet/server.php(219): require('/Users/lukas/Co...')
#70 {main}
```

</details></br>

**Lighthouse Version**

Lighthouse: v5.18.1
Laravel: v8.54.0

**Comment by spawnia** [comment]
You can use the following channels to ask support questions:
- [Use the laravel-lighthouse tag on Stackoverflow](https://stackoverflow.com/questions/tagged/laravel-lighthouse) 
- [Hop into Slack](https://join.slack.com/t/lighthouse-php/shared_invite/enQtMzc1NzQwNTUxMjk3LWMyZWRiNWFmZGUxZmRlNDJkMTQ2ZDA1NzQ1YjVkNTdmNWE1OTUyZjZiN2I2ZGQxNTNiZTZiY2JlNmY2MGUyNTQ)

This repository and the issue tracker are used to advance the development of Lighthouse.
Issues that are neither detailed bug reports nor well thought-out feature proposals will be closed.
