### ISSUE TITLE
Renamed id attributes are broken by v.5.35.0

### ISSUE THREAD

**Issue by victorRadu** [nuwave/lighthouse#2042]
**Describe the bug**
The optimisation introduced in **v5.35.0**:
_"Shortcut @belongsTo and @morphTo if the client only selects the ID of the relation"_
will produce an error if the id field is renamed.
issue appears in this commit: https://github.com/nuwave/lighthouse/commit/bef611f1eafb291940c13b807267db06e03dbee6#diff-579d0eaaec182969eb2da9dce6ac40681afd08e65c062cbe7913d53f4dcaf968R40

**Example:**
we use a uuid field in the backend for the public id and an autoincrement id for the relation in the db. We use @rename to publish the uuid as id. If you only select the Id of a relation it will currently throw an error: 
Cannot return null for non-nullable field \"User.id\"

**Expected behavior/Solution**
if the id field is renamed the relation must be loaded as well, not only if other fields are queried

**Steps to reproduce**

1. create two models, one with a "belongs to" relationship
2. rename the id field to another field than the one used in the DB relation
3. Only query the id of the related object

**Output/Logs**

<details><summary>Click to expand</summary>

```
[2022-01-27 10:51:47] testing.ERROR: Cannot return null for non-nullable field "User.id". {"userId":1,"exception":"[object] (GraphQL\\Error\\InvariantViolation(code: 0): Cannot return null for non-nullable field \"User.id\". at /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php:748)
[stacktrace]
#0 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue()
#1 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError()
#2 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField()
#3 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\\Executor\\ReferenceExecutor->executeFields()
#4 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\\Executor\\ReferenceExecutor->collectAndExecuteSubfields()
#5 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(793): GraphQL\\Executor\\ReferenceExecutor->completeObjectValue()
#6 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(741): GraphQL\\Executor\\ReferenceExecutor->completeValue()
#7 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue()
#8 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError()
#9 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField()
#10 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1145): GraphQL\\Executor\\ReferenceExecutor->executeFields()
#11 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1106): GraphQL\\Executor\\ReferenceExecutor->collectAndExecuteSubfields()
#12 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(793): GraphQL\\Executor\\ReferenceExecutor->completeObjectValue()
#13 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(654): GraphQL\\Executor\\ReferenceExecutor->completeValue()
#14 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(557): GraphQL\\Executor\\ReferenceExecutor->completeValueCatchingError()
#15 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(1195): GraphQL\\Executor\\ReferenceExecutor->resolveField()
#16 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(264): GraphQL\\Executor\\ReferenceExecutor->executeFields()
#17 /var/www/html/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php(215): GraphQL\\Executor\\ReferenceExecutor->executeOperation()
#18 /var/www/html/vendor/webonyx/graphql-php/src/Executor/Executor.php(156): GraphQL\\Executor\\ReferenceExecutor->doExecute()
#19 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(162): GraphQL\\Executor\\Executor::promiseToExecute()
#20 /var/www/html/vendor/webonyx/graphql-php/src/GraphQL.php(94): GraphQL\\GraphQL::promiseToExecute()
#21 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(268): GraphQL\\GraphQL::executeQuery()
#22 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(203): Nuwave\\Lighthouse\\GraphQL->executeParsedQuery()
#23 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(162): Nuwave\\Lighthouse\\GraphQL->parseAndExecuteQuery()
#24 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(121): Nuwave\\Lighthouse\\GraphQL->executeOperation()
#25 /var/www/html/vendor/nuwave/lighthouse/src/Support/Utils.php(99): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}()
#26 /var/www/html/vendor/nuwave/lighthouse/src/GraphQL.php(120): Nuwave\\Lighthouse\\Support\\Utils::applyEach()
#27 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->__invoke()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#33 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#38 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AttemptAuthentication.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AttemptAuthentication->handle()
#40 /var/www/html/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#59 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#61 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(510): Illuminate\\Foundation\\Http\\Kernel->handle()
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(476): Illuminate\\Foundation\\Testing\\TestCase->call()
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php(335): Illuminate\\Foundation\\Testing\\TestCase->json()
#69 /var/www/html/vendor/nuwave/lighthouse/src/Testing/MakesGraphQLRequests.php(79): Illuminate\\Foundation\\Testing\\TestCase->postJson()
#70 /var/www/html/vendor/nuwave/lighthouse/src/Testing/MakesGraphQLRequests.php(62): Tests\\Feature\\Organisation\\OrganisationTest->postGraphQL()
#71 /var/www/html/tests/Feature/Organisation/OrganisationTest.php(269): Tests\\Feature\\Organisation\\OrganisationTest->graphQL()
#72 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1545): Tests\\Feature\\Organisation\\OrganisationTest->test_get_organisation()
#73 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1151): PHPUnit\\Framework\\TestCase->runTest()
#74 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(726): PHPUnit\\Framework\\TestCase->runBare()
#75 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(903): PHPUnit\\Framework\\TestResult->run()
#76 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\\Framework\\TestCase->run()
#77 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(677): PHPUnit\\Framework\\TestSuite->run()
#78 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(670): PHPUnit\\Framework\\TestSuite->run()
#79 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\\TextUI\\TestRunner->run()
#80 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\\TextUI\\Command->run()
#81 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\\TextUI\\Command::main()
#82 {main}
```

</details></br>

**Lighthouse Version** 5.38.0

**Comment by pyrou** [comment]
Duplicates #2033
