### ISSUE TITLE
using @hasMany throws an error because $parent is not set

### ISSUE THREAD

**Issue by maarten00** [nuwave/lighthouse#205]
**Describe the bug**
I want to retrieve a list of clubs using the hasMany directive, because I don't need pagination.
The `@paginate` directive works as expected, the `@hasMany` does not. It throws a 500 error on this query: 

```graphql
query{
  clubs(name: "MHCO", count: 100, page: 1){
    data
    {
      name
    }
  }
  clubsByName(name: "MHCO"){
    name
  }
}
``` 
(The first query works, the second one throws the error)

**Expected behavior**
It should retrieve a list of clubs matching my arguments (or without any arguments) without pagination

**Schema**

```graphql
type Query {
    clubs(name: String @eq): [Club!]! @paginate(model: "Club")
    clubsByName(name: String @eq): [Club] @hasMany(model: "Club")
}
```

**Output/Logs**

I have attached the stacktrace below. I tracked down the error, it occurs in `HasManyDirective.php` on line 66 in the `resolveField()` function, because `$parent` is not set.  

```
[2018-07-17 05:58:29] local.INFO: GraphQL Error: {"code":0,"message":"Call to a member function getKey() on null","trace":"#0 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(857): GraphQL\\Error\\Error::createLocatedError(Object(Error), Object(ArrayObject), Array)
#1 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(799): GraphQL\\Executor\\Executor->completeValueWithLocatedError(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Error))
#2 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(721): GraphQL\\Executor\\Executor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(Error))
#3 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(442): GraphQL\\Executor\\Executor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#4 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(324): GraphQL\\Executor\\Executor->executeFields(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Array, Object(ArrayObject))
#5 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(287): GraphQL\\Executor\\Executor->executeOperation(Object(GraphQL\\Language\\AST\\OperationDefinitionNode), NULL)
#6 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php(59): GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}(Array, Array)
#7 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(288): GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter->create(Object(Closure))
#8 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/Executor/Executor.php(151): GraphQL\\Executor\\Executor->doExecute()
#9 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/GraphQL.php(155): GraphQL\\Executor\\Executor::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), Object(GraphQL\\Language\\AST\\DocumentNode), NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL)
#10 /Users/maarten/workspace/graphqlproject/vendor/webonyx/graphql-php/src/GraphQL.php(86): GraphQL\\GraphQL::promiseToExecute(Object(GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter), Object(GraphQL\\Type\\Schema), 'query{\
  clubs(...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL, NULL, NULL)
#11 /Users/maarten/workspace/graphqlproject/vendor/nuwave/lighthouse/src/GraphQL.php(149): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), 'query{\
  clubs(...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array)
#12 /Users/maarten/workspace/graphqlproject/vendor/nuwave/lighthouse/src/GraphQL.php(108): Nuwave\\Lighthouse\\GraphQL->queryAndReturnResult('query{\
  clubs(...', Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL)
#13 /Users/maarten/workspace/graphqlproject/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(44): Nuwave\\Lighthouse\\GraphQL->execute('query{\
  clubs(...', Object(Nuwave\\Lighthouse\\Schema\\Context), Array)
#14 [internal function]: Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->query(Object(Illuminate\\Http\\Request))
#15 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#16 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('query', Array)
#17 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController), 'query')
#18 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#19 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#20 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/maarten/workspace/graphqlproject/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 /Users/maarten/workspace/graphqlproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#46 /Users/maarten/workspace/graphqlproject/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#47 {main}"} 
```

**Environment**

Lighthouse Version: 2.1.1
Laravel Version: 5.6.27
PHP Version: 7.2.1 (but the issue also occurs on 7.1.12)

**Comment by spawnia** [comment]
Hey, thanks for reaching out.

**Solution**

Use the new `@all` directive, which simply retrieves all the models. I just made a PR
that enables filters to be used with it, should be merged into master soon. @chrissm79 

**Explanation**

The `@hasMany` directive works for sub-fields of a type that corresponds to a model, e.g.:

````grapqhl
type User {
   posts: [Post!] @hasMany
}
````

Since you are trying to apply it on a root query field, i actually expect this to error.
