### ISSUE TITLE
Programmatically defined types cannot be found or overwrited while parsing .graphql file

### ISSUE THREAD

**Issue by ddzobov** [nuwave/lighthouse#2414]
**Describe the bug**

Programmatically defined types cannot be found while parsing .graphql file

**Steps to reproduce**

I've added to TypeRegistry programatically type Rack ($typeRegistry->register() or $typeRegistry->registerLazy() - same behavior):

```
extend type Query {
    rack(
        id: ID! @whereKey
     ): Rack @find

    racks(
        ids: [ID!] @whereKey
        search: String @search
    ): [Rack!]! @paginate
}

extend type Mutation {
    rackUpsert(
        id: ID
        name: String!
        size: Int!
    ): Rack @upsert

    rackDelete(
        id: ID! @whereKey
    ): Rack @delete
}

```

```
[2023-06-18 18:13:07] local.ERROR: Type 'Rack' on 'racks' can not be found in the schema.' {"exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): Type 'Rack' on 'racks' can not be found in the schema.' at /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTHelper.php:348)
```

Next, i've added type definition into .graphql file:

```
type Rack {
    id: ID!
    name: String!
    created_at: DateTime!
    updated_at: DateTime!
}
```

```
# [2023-06-18 18:09:25] local.ERROR: Tried to register a type that is already present in the schema: Datacenter. Use overwrite() to ignore existing types. {"exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): Tried to register a type that is already present in the schema: Datacenter. Use overwrite() to ignore existing types. at /var/www/vendor/nuwave/lighthouse/src/Schema/TypeRegistry.php:84)
```

**Lighthouse Version**

6.10.0

**Comment by spawnia** [comment]
> [2023-06-18 18:13:07] local.ERROR: Type 'Rack' on 'racks' can not be found in the schema.' {"exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): Type 'Rack' on 'racks' can not be found in the schema.' at /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTHelper.php:348)

What is the stacktrace of this error?

**Comment by ddzobov** [comment]
> > [2023-06-18 18:13:07] local.ERROR: Type 'Rack' on 'racks' can not be found in the schema.' {"exception":"[object] (Nuwave\Lighthouse\Exceptions\DefinitionException(code: 0): Type 'Rack' on 'racks' can not be found in the schema.' at /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTHelper.php:348)
> 
> What is the stacktrace of this error?

```
[2023-06-19 09:47:33] local.ERROR: Type 'Rack' on 'racks' can not be found in the schema.' {"exception":"[object] (Nuwave\\Lighthouse\\Exceptions\\DefinitionException(code: 0): Type 'Rack' on 'racks' can not be found in the schema.' at /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTHelper.php:348)
[stacktrace]
#0 /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTHelper.php(355): Nuwave\\Lighthouse\\Schema\\AST\\ASTHelper::underlyingType(Object(GraphQL\\Language\\AST\\FieldDefinitionNode))
#1 /var/www/vendor/nuwave/lighthouse/src/Schema/Directives/BaseDirective.php(149): Nuwave\\Lighthouse\\Schema\\AST\\ASTHelper::modelName(Object(GraphQL\\Language\\AST\\FieldDefinitionNode))
#2 /var/www/vendor/nuwave/lighthouse/src/Pagination/PaginateDirective.php(125): Nuwave\\Lighthouse\\Schema\\Directives\\BaseDirective->getModelClass()
#3 /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTBuilder.php(200): Nuwave\\Lighthouse\\Pagination\\PaginateDirective->manipulateFieldDefinition(Object(Nuwave\\Lighthouse\\Schema\\AST\\DocumentAST), Object(GraphQL\\Language\\AST\\FieldDefinitionNode), Object(GraphQL\\Language\\AST\\ObjectTypeDefinitionNode))
#4 /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTBuilder.php(74): Nuwave\\Lighthouse\\Schema\\AST\\ASTBuilder->applyFieldManipulators()
#5 /var/www/vendor/nuwave/lighthouse/src/Schema/AST/ASTBuilder.php(50): Nuwave\\Lighthouse\\Schema\\AST\\ASTBuilder->build()
#6 /var/www/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php(27): Nuwave\\Lighthouse\\Schema\\AST\\ASTBuilder->documentAST()
#7 /var/www/vendor/nuwave/lighthouse/src/GraphQL.php(112): Nuwave\\Lighthouse\\Schema\\SchemaBuilder->schema()
#8 /var/www/vendor/nuwave/lighthouse/src/GraphQL.php(86): Nuwave\\Lighthouse\\GraphQL->executeParsedQuery(Object(GraphQL\\Language\\AST\\DocumentNode), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL)
#9 /var/www/vendor/nuwave/lighthouse/src/GraphQL.php(212): Nuwave\\Lighthouse\\GraphQL->executeQueryString('query {\\n    # s...', Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext), Array, NULL, NULL)
#10 /var/www/vendor/nuwave/lighthouse/src/GraphQL.php(177): Nuwave\\Lighthouse\\GraphQL->executeOperation(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#11 /var/www/vendor/nuwave/lighthouse/src/Support/Utils.php(107): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}(Object(GraphQL\\Server\\OperationParams))
#12 /var/www/vendor/nuwave/lighthouse/src/GraphQL.php(173): Nuwave\\Lighthouse\\Support\\Utils::mapEach(Object(Closure), Object(GraphQL\\Server\\OperationParams))
#13 /var/www/vendor/nuwave/lighthouse/src/Http/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations(Object(GraphQL\\Server\\OperationParams), Object(Nuwave\\Lighthouse\\Execution\\HttpGraphQLContext))
#14 /var/www/vendor/illuminate/container/BoundMethod.php(36): Nuwave\\Lighthouse\\Http\\GraphQLController->__invoke(Object(Laravel\\Lumen\\Http\\Request), Object(Nuwave\\Lighthouse\\GraphQL), Object(Illuminate\\Events\\Dispatcher), Object(Laragraph\\Utils\\RequestParser), Object(Nuwave\\Lighthouse\\Execution\\SingleResponse), Object(Nuwave\\Lighthouse\\Execution\\ContextFactory))
#15 /var/www/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /var/www/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 /var/www/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#18 /var/www/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#19 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(391): Illuminate\\Container\\Container->call(Array, Array)
#20 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(333): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#21 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(284): Laravel\\Lumen\\Application->callControllerAction(Array)
#22 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(264): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#23 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#24 /var/www/vendor/nuwave/lighthouse/src/Http/Middleware/AttemptAuthentication.php(22): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#25 /var/www/vendor/illuminate/pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\AttemptAuthentication->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#26 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#27 /var/www/vendor/nuwave/lighthouse/src/Http/Middleware/AcceptJson.php(24): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#28 /var/www/vendor/illuminate/pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\AcceptJson->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#29 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#30 /var/www/vendor/illuminate/pipeline/Pipeline.php(116): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#31 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(263): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#33 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#34 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(48): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#35 /var/www/vendor/illuminate/http/Middleware/HandleCors.php(62): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#36 /var/www/vendor/illuminate/pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))
#37 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#38 /var/www/vendor/illuminate/pipeline/Pipeline.php(116): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#39 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(428): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(167): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#41 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch(NULL)
#42 /var/www/public/index.php(28): Laravel\\Lumen\\Application->run()
#43 {main}
"} 
```

**Comment by spawnia** [comment]
Fixed with https://github.com/nuwave/lighthouse/releases/tag/v6.10.1. Please consider sponsoring.
