### ISSUE TITLE
Exception Undefined array key "schemaExtensions"

### ISSUE THREAD

**Issue by SuperDJ** [nuwave/lighthouse#2491]
**Describe the bug**

It throws the following error: Undefined array key "schemaExtensions". The schema is validated and valid.

**Expected behavior/Solution**

Don't throw

**Output/Logs**

<details><summary>Click to expand</summary>

```
[2023-12-20 10:16:02] dev.ERROR: Undefined array key "schemaExtensions" {"userId":22,"exception":"[object] (ErrorException(code: 0): Undefined array key \"schemaExtensions\" at vendor/nuwave/lighthouse/src/Schema/AST/DocumentAST.php:235)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 vendor/nuwave/lighthouse/src/Schema/AST/DocumentAST.php(235): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 vendor/nuwave/lighthouse/src/Schema/AST/DocumentAST.php(211): Nuwave\\Lighthouse\\Schema\\AST\\DocumentAST->hydrateFromArray()
#3 vendor/nuwave/lighthouse/src/Schema/AST/ASTCache.php(59): Nuwave\\Lighthouse\\Schema\\AST\\DocumentAST::fromArray()
#4 vendor/nuwave/lighthouse/src/Schema/AST/ASTBuilder.php(52): Nuwave\\Lighthouse\\Schema\\AST\\ASTCache->fromCacheOrBuild()
#5 vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php(27): Nuwave\\Lighthouse\\Schema\\AST\\ASTBuilder->documentAST()
#6 vendor/nuwave/lighthouse/src/GraphQL.php(112): Nuwave\\Lighthouse\\Schema\\SchemaBuilder->schema()
#7 vendor/nuwave/lighthouse/src/GraphQL.php(86): Nuwave\\Lighthouse\\GraphQL->executeParsedQuery()
#8 vendor/nuwave/lighthouse/src/GraphQL.php(212): Nuwave\\Lighthouse\\GraphQL->executeQueryString()
#9 vendor/nuwave/lighthouse/src/GraphQL.php(177): Nuwave\\Lighthouse\\GraphQL->executeOperation()
#10 vendor/nuwave/lighthouse/src/Support/Utils.php(107): Nuwave\\Lighthouse\\GraphQL->Nuwave\\Lighthouse\\{closure}()
#11 vendor/nuwave/lighthouse/src/GraphQL.php(173): Nuwave\\Lighthouse\\Support\\Utils::mapEach()
#12 vendor/nuwave/lighthouse/src/Http/GraphQLController.php(32): Nuwave\\Lighthouse\\GraphQL->executeOperationOrOperations()
#13 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Nuwave\\Lighthouse\\Http\\GraphQLController->__invoke()
#14 vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(21): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#15 vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php(19): Sentry\\Laravel\\Tracing\\Routing\\TracingControllerDispatcherTracing->Sentry\\Laravel\\Tracing\\Routing\\{closure}()
#16 vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(20): Sentry\\Laravel\\Tracing\\Routing\\TracingRoutingDispatcher->wrapRouteDispatch()
#17 vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Sentry\\Laravel\\Tracing\\Routing\\TracingControllerDispatcherTracing->dispatch()
#18 vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#19 vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\\Routing\\Route->run()
#20 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#21 vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 app/Http/Middleware/OneOfMiddleware.php(20): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\OneOfMiddleware->handle()
#24 vendor/nuwave/lighthouse/src/Http/Middleware/LogGraphQLQueries.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\LogGraphQLQueries->handle()
#26 vendor/nuwave/lighthouse/src/Http/Middleware/AttemptAuthentication.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\AttemptAuthentication->handle()
#28 vendor/nuwave/lighthouse/src/Http/Middleware/AcceptJson.php(24): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\AcceptJson->handle()
#30 vendor/nuwave/lighthouse/src/Http/Middleware/EnsureXHR.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Nuwave\\Lighthouse\\Http\\Middleware\\EnsureXHR->handle()
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#34 vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#35 vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#36 vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#37 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#39 vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Http\\SetRequestIpMiddleware->handle()
#41 vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Http\\SetRequestMiddleware->handle()
#43 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#46 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#48 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#49 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#51 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#53 vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#55 vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#57 vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(97): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Tracing\\Middleware->handle()
#59 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#61 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#62 public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle()
#63 {main}
"} 
```

</details></br>

**Lighthouse Version**
v6.29.1

**Comment by spawnia** [comment]
Your schema cache is out of date, you need to refresh it when upgrading Lighthouse.
