### ISSUE TITLE
Error when using non-primitive Types in interfaces

### ISSUE THREAD

**Issue by jbbr** [nuwave/lighthouse#324]
**Describe the bug**

When using non-primitive types like custom Scalars, object types or other interfaces within an interface an exception is thrown. The exeption is thrown while building the AST/resolving types.

In the following example schema I'm using `DateTime` scalar as an example.
Same problem occurs when using a different interface, e.g for a relation on the `UserInterface`.

**Expected behavior**

I expect the schema to "just work" as I don't see an issue with the schema.
Maybe I'm missing something?

**Schema**

```graphql
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

interface UserInterface {
    id: ID!
    email: String!
    created_at: DateTime!
}

type User implements UserInterface {
    id: ID!
    email: String!
    created_at: DateTime!

    name: String!
}

type Query {
    me: User @auth
}

```

**Output/Logs**

Exception trace when hitting `/graphql` route
```bash
[2018-09-16 18:37:18] local.ERROR: Return value of Nuwave\Lighthouse\Schema\Resolvers\NodeResolver::convertNamedType() must be an instance of GraphQL\Type\Definition\Type, null returned {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of Nuwave\\Lighthouse\\Schema\\Resolvers\\NodeResolver::convertNamedType() must be an instance of GraphQL\\Type\\Definition\\Type, null returned at /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Resolvers/NodeResolver.php:92)
[stacktrace]
#0 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Resolvers/NodeResolver.php(67): Nuwave\\Lighthouse\\Schema\\Resolvers\\NodeResolver->convertNamedType(Object(GraphQL\\Language\\AST\\NamedTypeNode))
#1 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Resolvers/NodeResolver.php(54): Nuwave\\Lighthouse\\Schema\\Resolvers\\NodeResolver->extractTypeFromNode(Object(GraphQL\\Language\\AST\\NamedTypeNode))
#2 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Resolvers/NodeResolver.php(35): Nuwave\\Lighthouse\\Schema\\Resolvers\\NodeResolver->fromNode(Object(GraphQL\\Language\\AST\\NamedTypeNode), Array)
#3 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Resolvers/NodeResolver.php(19): Nuwave\\Lighthouse\\Schema\\Resolvers\\NodeResolver->fromNode(Object(GraphQL\\Language\\AST\\NonNullTypeNode))
#4 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php(27): Nuwave\\Lighthouse\\Schema\\Resolvers\\NodeResolver::resolve(Object(GraphQL\\Language\\AST\\NonNullTypeNode))
#5 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Support/Traits/HandlesTypes.php(181): Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory->handle(Object(Nuwave\\Lighthouse\\Schema\\Values\\FieldValue))
#6 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1025): Nuwave\\Lighthouse\\Schema\\Factories\\NodeFactory->Nuwave\\Lighthouse\\Support\\Traits\\{closure}(Object(GraphQL\\Language\\AST\\FieldDefinitionNode), 2)
#7 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Support/Traits/HandlesTypes.php(183): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#8 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php(143): Nuwave\\Lighthouse\\Schema\\Factories\\NodeFactory->getFields(Object(Nuwave\\Lighthouse\\Schema\\Values\\NodeValue))
#9 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php(92): Nuwave\\Lighthouse\\Schema\\Factories\\NodeFactory->interface(Object(Nuwave\\Lighthouse\\Schema\\Values\\NodeValue))
#10 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/Factories/NodeFactory.php(41): Nuwave\\Lighthouse\\Schema\\Factories\\NodeFactory->resolveType(Object(Nuwave\\Lighthouse\\Schema\\Values\\NodeValue))
#11 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php(110): Nuwave\\Lighthouse\\Schema\\Factories\\NodeFactory->handle(Object(Nuwave\\Lighthouse\\Schema\\Values\\NodeValue))
#12 [internal function]: Nuwave\\Lighthouse\\Schema\\SchemaBuilder->Nuwave\\Lighthouse\\Schema\\{closure}(Object(GraphQL\\Language\\AST\\InterfaceTypeDefinitionNode), 1)
#13 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Support/Collection.php(948): array_map(Object(Closure), Array, Array)
#14 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php(111): Illuminate\\Support\\Collection->map(Object(Closure))
#15 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Schema/SchemaBuilder.php(42): Nuwave\\Lighthouse\\Schema\\SchemaBuilder->convertTypes(Object(Nuwave\\Lighthouse\\Schema\\AST\\DocumentAST))
#16 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/GraphQL.php(190): Nuwave\\Lighthouse\\Schema\\SchemaBuilder->build(Object(Nuwave\\Lighthouse\\Schema\\AST\\DocumentAST))
#17 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/GraphQL.php(118): Nuwave\\Lighthouse\\GraphQL->buildSchema()
#18 /home/user/dev/lighthouse_test/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(21): Nuwave\\Lighthouse\\GraphQL->prepSchema()
#19 [internal function]: Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->__construct(Object(Illuminate\\Http\\Request))
#20 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): ReflectionClass->newInstanceArgs(Array)
#21 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Container/Container.php(646): Illuminate\\Container\\Container->build('Nuwave\\\\Lighthou...')
#22 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Container/Container.php(601): Illuminate\\Container\\Container->resolve('Nuwave\\\\Lighthou...', Array)
#23 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(733): Illuminate\\Container\\Container->make('Nuwave\\\\Lighthou...', Array)
#24 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(226): Illuminate\\Foundation\\Application->make('Nuwave\\\\Lighthou...')
#25 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(796): Illuminate\\Routing\\Route->getController()
#26 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Route.php(757): Illuminate\\Routing\\Route->controllerMiddleware()
#27 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->gatherMiddleware()
#28 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#29 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#30 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#31 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#32 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#33 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/user/dev/lighthouse_test/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 /home/user/dev/lighthouse_test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#52 /home/user/dev/lighthouse_test/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))

```

**Environment**

Lighthouse Version: v2.2
Laravel Version: v5.7.3
PHP Version: 7.2.9

**Additional context**

When resolving the requested `DateTime` type in `Schema\Resolvers\NodeResolver@convertNamedType`, the switch defaults to using the `TypeRegistry` for resolving the type (`graphql()->types()->get('DateTime')`).
But the `TypeRegistry` returns `null` at that time.

I tried to replicate the behavior in an integration test. For some reason it did not fail in the test.

<details><summary>Here the test case I've written:</summary>
<p>

#### InterfaceTest

```php
   // tests/Integration/Schema/Types/InterfaceTest.php
    public function itCanResolveNonPrimitivesInInterfaces()
    {
        // This creates one team with it
        factory(User::class)->create();

        $schema = '
        scalar DateTime @scalar(class: "' . addslashes(DateTime::class) . '")

        interface Timestamped {
            created_at: DateTime!
        }
        type User implements Timestamped {
            id: ID!
            created_at: DateTime!
        }
        type Team implements Timestamped {
            created_at: DateTime!
        }
        
        type Query {
            timestampedThings: [Timestamped!]! @field(resolver: "' . addslashes(self::class) . '@fetchResults")
        }
        ';
        $query = '
        {
            timestampedThings {
                created_at
                ... on User {
                    id
                }
            }
        }
        ';
        $result = $this->execute($schema, $query);

        $this->assertCount(2, array_get($result, 'data.timestampedThings'));
        $this->assertArrayHasKey('created_at', array_get($result, 'data.timestampedThings.0'));
        $this->assertArrayHasKey('id', array_get($result, 'data.timestampedThings.0'));
        $this->assertArrayHasKey('created_at', array_get($result, 'data.timestampedThings.1'));
        $this->assertArrayNotHasKey('id', array_get($result, 'data.timestampedThings.1'));
    }
```

</p>
</details>

**Comment by spawnia** [comment]
Can you try the latest version on the master branch?

Also, do you have schema caching active?

**Comment by jbbr** [comment]
@spawnia to answer your questions:

- do you have schema caching active
**No**

- Can you try the latest version on the master branch?
I ran my test case on the master branch and it succeeded. So maybe the behavior is changed/fixed in master.
I don't see a reason why I would need a resolver for `created_at: DateTime` (scalar) but not for `created_at: String`

**Comment by spawnia** [comment]
If you want some massive performance gains, especially for large schemas, consider caching.

Well, String is built in but DateTime is not.
