### ISSUE TITLE
Error to try define a Scalar Type for generic object

### ISSUE THREAD

**Issue by carlospalacin** [nuwave/lighthouse#350]
**Environment**
Lighthouse Version: 2.2
Laravel Version: 5.7.6
PHP Version: 7.2.1

Hi! 
I had migrate from Folkloreatelier/laravel-graphql and I am very happy with the results, great job!!

But I have found a problem with a Scalar type. I Handle data that contains variable fields, for these cases I have created a Scalar Type Object.

```
<?php namespace Syscover\Core\GraphQL\Types\Scalars;

use GraphQL\Type\Definition\ScalarType;

class ObjectType extends ScalarType
{
    public $name = "Object";
    public $description = "Object scalar type, type that encapsulates for any object";

    public function serialize($value)
    {
        return $value;
    }

    public function parseValue($value)
    {
        return $value;
    }

    public function parseLiteral($valueNode, array $variables = null)
    {
        return $valueNode->value;
    }
}
```

With this Scalar type I could encapsulate any object in Folkloreatelier/laravel-graphql and it worked well for any case. Now with lighthouse only work with simple objects.

If I have this input definition:
```
input ImageInput {
    name: String
    height: Int
    width: Int
    # this field contain variable fields
    exif: Object 
}
```
I can pass aguments like that:
```
let args = {
	name: 'image.jpg',
	height: 300,
    width: 200,
    exif: {
    	Make: "Canon",
    	Flash: 16, 
    	Model: "Canon EOS 5DS"
    }
}
```
this above argument Scalar Type Object work fine, but if object has various depth levels, like that:

```
let args = {
	name: 'image.jpg',
	height: 300,
    width: 200,
    exif: {
    	Make: "Canon",
    	Flash: 16, 
    	Model: "Canon EOS 5DS",
    	comuted: {
    		width: 500,
    		height: 600,
    		IsColor: 1
    	}
    }
}
```
I get this error:

```
GraphQL Error: {"code":0,"message":"Argument 1 passed to Nuwave\\Lighthouse\\Schema\\Factories\\RuleFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}() must be an instance of GraphQL\\Language\\AST\\Node, null given","trace":"#0 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Executor.php(888): GraphQL\\Error\\Error::createLocatedError(Object(TypeError), Object(ArrayObject), Array)
#1 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Executor.php(830): GraphQL\\Executor\\Executor->completeValueWithLocatedError(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(TypeError))
#2 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Executor.php(752): GraphQL\\Executor\\Executor->completeValueCatchingError(Object(GraphQL\\Type\\Definition\\ListOfType), Object(ArrayObject), Object(GraphQL\\Type\\Definition\\ResolveInfo), Array, Object(TypeError))
#3 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Executor.php(429): GraphQL\\Executor\\Executor->resolveField(Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject), Array)
#4 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Executor.php(446): GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}(Array, 'adminCropAttach...', Array, Object(GraphQL\\Type\\Definition\\ObjectType), NULL, Object(ArrayObject))
#5 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(135): GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}(Array)
#6 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(35): GraphQL\\Executor\\Promise\\Adapter\\SyncPromise->GraphQL\\Executor\\Promise\\Adapter\\{closure}()
#7 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php(140): GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()
#8 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/webonyx/graphql-php/src/GraphQL.php(88): GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter->wait(Object(GraphQL\\Executor\\Promise\\Promise))
#9 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/nuwave/lighthouse/src/GraphQL.php(173): GraphQL\\GraphQL::executeQuery(Object(GraphQL\\Type\\Schema), 'mutation AdminC...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), Array, 'AdminCropAttach...', NULL, Array)
#10 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/nuwave/lighthouse/src/GraphQL.php(133): Nuwave\\Lighthouse\\GraphQL->queryAndReturnResult('mutation AdminC...', Object(Nuwave\\Lighthouse\\Schema\\Context), Array, NULL)
#11 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(46): Nuwave\\Lighthouse\\GraphQL->execute('mutation AdminC...', Object(Nuwave\\Lighthouse\\Schema\\Context), Array)
#12 [internal function]: Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->query(Object(Illuminate\\Http\\Request))
#13 /Users/Carlos/Documents/Webserver/api.pulsar.local/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
....
```

Is it not possible that lighthouse allows a Scalar Object with illimited depth?
Or am I defining the Scalar Object wrong?

**Comment by enzonotario** [comment]
Hi! As I understand, talking in slack, that is not possible nor a good practice. What you can do is use a `JSON` scalar, like this:
```
use GraphQL\Error\Error;
use GraphQL\Language\AST\Node;
use GraphQL\Type\Definition\InputType;
use GraphQL\Type\Definition\ScalarType;

class JsonScalar extends ScalarType implements InputType
{
    public $name = 'JSON';

    public function serialize($value)
    {
        if (is_string($value)) {
            $value = json_decode($value, true);
        }

        return $value;
    }

    /**
     * Parses an externally provided value (query variable) to use as an input
     *
     * In the case of an invalid value this method must throw an Exception
     *
     * @param mixed $value
     *
     * @return mixed
     * @throws Error
     */
    public function parseValue($value)
    {
        return $value;
    }

    /**
     * Parses an externally provided literal value (hardcoded in GraphQL query) to use as an input
     *
     * In the case of an invalid node or value this method must throw an Exception
     *
     * @param Node       $valueNode
     * @param array|null $variables
     *
     * @return mixed
     * @throws \Exception
     */
    public function parseLiteral($valueNode, array $variables = null)
    {
        return $valueNode->value;
    }
}
```

and in the frontend, you have to pass a stringify json, like:
```
{
    name: 'image.jpg',
    height: 300,
    width: 200,
    exif: "{
    	\"Make\": \"Canon\",
    	\"Flash\": \"16\", 
    	\"Model\": \"Canon EOS 5DS\"
    }"
}
```

**Comment by spawnia** [comment]
Note what the GraphQL specification says about Scalar types: http://facebook.github.io/graphql/June2018/#sec-Scalars

@enzonotario is correct in his assessment, in this case something like a JSON scalar type would be possible.

I recommend you to try and write idiomatic GraphQL instead, which is strongly typed.

BTW, i am currently working on a set of custom scalar types, feel free to pop over and hit me up with your PR's, ideas, whatever. https://github.com/mll-lab/graphql-php-scalars

**Comment by spawnia** [comment]
You can try the https://github.com/mll-lab/graphql-php-scalars/blob/master/src/Mixed.php custom scalar. There are a bunch of weird edge cases, where GraphQL literals and JSON provided variables behave a bit diffently, i smoothed it out.

Planning to add a JSON type to the package soon, feel free to contribute.
