### ISSUE TITLE
Fetching relationships gives SQLSTATE[42601] error

### ISSUE THREAD

**Issue by KubqoA** [nuwave/lighthouse#89]
Hello,
I was following the walkthrough for lighthouse on youtube, but I am running onto SQLSTATE error when I want to use relationships.

This is my `schema.graphql` file:
```
enum Type {
    ADMIN @enum(value: "admin")
    CUSTOMER @enum(value: "customer")
}

type User {
    id: ID!
    name: String!
    email: String!
    type: Type!
    created_at: String!
    updated_at: String
}

type Customer {
    id: ID!
    email: String!
    phone: String
    user: User @belongsTo
}

type Query {
    customers: [Customer!]! @field(resolver: "App\\Http\\GraphQL\\Query@customers")
}
```

When I call this query:
```
{
  customers {
    id
    user {
      name
    }
  }
}
```

The return values are:
```
{
  "data": {
    "customers": [
      {
        "id": "1",
        "user": null
      }
    ]
  },
  "errors": [
    {
      "message": "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \".\"\nLINE 1: SELECT `users`.* FROM ((select * from \"users\" where \"users\"....\n                      ^ (SQL: SELECT `users`.* FROM ((select * from \"users\" where \"users\".\"id\" in (1))) AS `users`)",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ]
    }
  ]
}
```

And `laravel.log` contains the following info:
```
[2018-04-24 02:54:08] local.INFO: GraphQL Error: {"code":0,"message":"SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \".\"
LINE 1: SELECT `users`.* FROM ((select * from \"users\" where \"users\"....
                      ^ (SQL: SELECT `users`.* FROM ((select * from \"users\" where \"users\".\"id\" in (1))) AS `users`)","trace":"#0 /home/vagrant/code/kalsha/vendor/webonyx/graphql-php/src/Executor/Executor.php(850): GraphQL\\Error\\Error::createLocatedError(Object(Illuminate\\Database\\QueryException), Object(ArrayObject), Array)
#1 /home/vagrant/code/kalsha/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(144): GraphQL\\Executor\\Executor->GraphQL\\Executor\\{closure}(Object(Illuminate\\Database\\QueryException))
#2 /home/vagrant/code/kalsha/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromise.php(35): GraphQL\\Executor\\Promise\\Adapter\\SyncPromise->GraphQL\\Executor\\Promise\\Adapter\\{closure}()
#3 /home/vagrant/code/kalsha/vendor/webonyx/graphql-php/src/Executor/Promise/Adapter/SyncPromiseAdapter.php(140): GraphQL\\Executor\\Promise\\Adapter\\SyncPromise::runQueue()
#4 /home/vagrant/code/kalsha/vendor/webonyx/graphql-php/src/GraphQL.php(236): GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter->wait(Object(GraphQL\\Executor\\Promise\\Promise))
#5 /home/vagrant/code/kalsha/vendor/nuwave/lighthouse/src/GraphQL.php(122): GraphQL\\GraphQL::executeAndReturnResult(Object(GraphQL\\Type\\Schema), '{\
  customers {...', NULL, Object(Nuwave\\Lighthouse\\Schema\\Context), NULL)
#6 /home/vagrant/code/kalsha/vendor/nuwave/lighthouse/src/GraphQL.php(81): Nuwave\\Lighthouse\\GraphQL->queryAndReturnResult('{\
  customers {...', Object(Nuwave\\Lighthouse\\Schema\\Context), NULL, NULL)
#7 /home/vagrant/code/kalsha/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php(44): Nuwave\\Lighthouse\\GraphQL->execute('{\
  customers {...', Object(Nuwave\\Lighthouse\\Schema\\Context), NULL)
#8 [internal function]: Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController->query(Object(Illuminate\\Http\\Request))
#9 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#10 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('query', Array)
#11 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController), 'query')
#12 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#13 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Route->run()
#14 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(661): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#18 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(602): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#19 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Router.php(591): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#20 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#21 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#22 /home/vagrant/code/kalsha/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#39 /home/vagrant/code/kalsha/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#40 /home/vagrant/code/kalsha/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#41 {main}"} 
```

I am using PostgreSQL and running PHP 7.2.
How to get the relationships to work? I can't figure it out. Thanks for any help

**Comment by chrissm79** [comment]
@KubqoA It looks like Postgres doesn't like the query that's being performed on the `belongsTo` relationship. The `hasMany` and `belongsTo` uses a custom query builder to build queries so you don't run into an N+1 issue. However, it would appear that it only works on MySQL and will need to be refactored for Postgres. 

I'll have to swap out implementations of the Query Builder based on the selected database engine and run custom queries for different types. I'll let you know when I get this squared away. Thanks for reporting the issue!

**Comment by KubqoA** [comment]
You are the man! Thanks it works now. And thanks for quick reply!
